<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Hotel;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;


class HotelsTableSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    DB::table('hotels')->insert([
      [
        'user_id' => 2,
        'hotel_name' => 'Sunshine Hotel',
        'url' => 'https://sunshinehotel.com',
        'postal_code' => '100-0001',
        'prefecture' => 'Tokyo',
        'city' => 'Chiyoda',
        'address' => '東京都千代田区永田町2-4-14',
        'access' => '5 minutes from Kanda Station. Conveniently located near major train lines, with easy access to shopping, dining, and cultural landmarks.',
        'description' => 'A luxury hotel located in the heart of Tokyo. This elegant establishment offers state-of-the-art amenities, exceptional service, and breathtaking city views. Perfect for both business and leisure travelers, with spacious rooms and top-notch facilities.',
        'image_main' => 'images/hotel.jpg',
        'image_sub1' => 'images/hotel.jpg',
        'image_sub2' => 'images/hotel.jpg',
        'image_sub3' => 'images/hotel.jpg',
        'image_sub4' => 'images/hotel.jpg',
        'cancellation_period' => 3,
        'general_fee' => 10,
        'sameday_fee' => 20,
        'breakfast_price' => 15.50,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      // 他のホテルデータをここに追加
      [
        'user_id' => 4,
        'hotel_name' => 'Moonlight Inn',
        'url' => 'https://moonlightinn.com',
        'postal_code' => '150-0001',
        'prefecture' => 'Tokyo',
        'city' => 'Shibuya',
        'address' => '東京都中央区日本橋浜町2-58-2',
        'access' => '10 minutes from Shibuya Station. Located in a vibrant area with easy access to shopping, dining, and entertainment hotspots, perfect for urban explorers.',
        'description' => 'A cozy inn in Shibuya. This charming establishment offers a blend of modern comfort and local flavor. Guests can enjoy stylish rooms, excellent service, and proximity to Tokyo\'s lively cultural scene. The inn features a communal lounge with a library, complimentary breakfast, and guided tours of Shibuya\'s iconic attractions. Perfect for solo travelers and couples, it provides a welcoming and convenient base to explore one of Tokyo\'s most dynamic neighborhoods.',
        'image_main' => 'images/hotel.jpg',
        'image_sub1' => 'images/hotel.jpg',
        'image_sub2' => 'images/hotel.jpg',
        'image_sub3' => 'images/hotel.jpg',
        'image_sub4' => 'images/hotel.jpg',
        'cancellation_period' => 2,
        'general_fee' => 15,
        'sameday_fee' => 25,
        'breakfast_price' => 12.50,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'user_id' => 6,
        'hotel_name' => 'Star Hotel',
        'url' => 'https://starhotel.com',
        'postal_code' => '100-0002',
        'prefecture' => 'Tokyo',
        'city' => 'Chiyoda',
        'address' => '東京都品川区大井1-27-3',
        'access' => '8 minutes from Tokyo Station. Strategically located for business travelers with quick access to major corporate and financial districts.',
        'description' => 'A business hotel near Tokyo Station. This hotel combines functionality with comfort, featuring modern rooms equipped for productivity and a range of business-friendly amenities. Guests can utilize meeting rooms, high-speed internet, and concierge services. The hotel\'s central location allows easy access to Tokyo\'s key business hubs and cultural landmarks. With its efficient design and attentive staff, it ensures a seamless stay for professionals and tourists alike.',
        'image_main' => 'images/hotel.jpg',
        'image_sub1' => 'images/hotel.jpg',
        'image_sub2' => 'images/hotel.jpg',
        'image_sub3' => 'images/hotel.jpg',
        'image_sub4' => 'images/hotel.jpg',
        'cancellation_period' => 1,
        'general_fee' => 20,
        'sameday_fee' => 30,
        'breakfast_price' => 10.00,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'user_id' => 7,
        'hotel_name' => 'Galaxy Hotel',
        'url' => 'https://galaxyhotel.com',
        'postal_code' => '100-0003',
        'prefecture' => 'Kyoto',
        'city' => 'Chiyoda',
        'address' => '東京都中央区日本橋浜町2-58-2',
        'access' => '7 minutes from Otemachi Station. Situated in the heart of Tokyo\'s financial district, with panoramic city views and high-end facilities.',
        'description' => 'A high-end hotel with a view. This luxurious property offers elegantly designed rooms, impeccable service, and a range of exclusive amenities to cater to the discerning traveler. Guests can enjoy gourmet dining, a rooftop bar, and a state-of-the-art fitness center. Ideal for business travelers and leisure guests, the hotel provides an exquisite balance of comfort and sophistication.',
        'image_main' => 'images/hotel.jpg',
        'image_sub1' => 'images/hotel.jpg',
        'image_sub2' => 'images/hotel.jpg',
        'image_sub3' => 'images/hotel.jpg',
        'image_sub4' => 'images/hotel.jpg',
        'cancellation_period' => 2,
        'general_fee' => 25,
        'sameday_fee' => 35,
        'breakfast_price' => 18.00,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'user_id' => 8,
        'hotel_name' => 'Oceanview Resort',
        'url' => 'https://oceanviewresort.com',
        'postal_code' => '100-0004',
        'prefecture' => 'Kanagawa',
        'city' => 'Chiyoda',
        'address' => '神奈川県横浜市都筑区茅ヶ崎中央32-2',
        'access' => '15 minutes from Kudanshita Station. A tranquil retreat by the sea, perfect for relaxation and rejuvenation.',
        'description' => 'A seaside resort. Guests can unwind in spacious rooms with ocean views, indulge in gourmet dining, and take advantage of various recreational activities offered by the resort. The property features a private beach, water sports facilities, and wellness programs. Perfect for families and couples seeking a serene getaway, it offers a harmonious blend of luxury and nature.',
        'image_main' => 'images/hotel.jpg',
        'image_sub1' => 'images/hotel.jpg',
        'image_sub2' => 'images/hotel.jpg',
        'image_sub3' => 'images/hotel.jpg',
        'image_sub4' => 'images/hotel.jpg',
        'cancellation_period' => 5,
        'general_fee' => 10,
        'sameday_fee' => 20,
        'breakfast_price' => 20.00,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'user_id' => 9,
        'hotel_name' => 'Mountain Lodge',
        'url' => 'https://mountainlodge.com',
        'postal_code' => '100-0005',
        'prefecture' => 'Hokkaido',
        'city' => 'Chiyoda',
        'address' => '北海道網走市新町1-3-3',
        'access' => '10 minutes from Akasaka Station. Set in a serene mountainous area, providing a perfect escape from the city\'s hustle and bustle.',
        'description' => 'A lodge in the mountains. This hidden gem offers a cozy ambiance, personalized service, and stunning natural surroundings. Ideal for nature lovers and those seeking tranquility. The lodge provides guided hiking tours, farm-to-table dining experiences, and a relaxing onsen for ultimate rejuvenation. Its picturesque location and warm hospitality create an unforgettable retreat..',
        'image_main' => 'images/hotel.jpg',
        'image_sub1' => 'images/hotel.jpg',
        'image_sub2' => 'images/hotel.jpg',
        'image_sub3' => 'images/hotel.jpg',
        'image_sub4' => 'images/hotel.jpg',
        'cancellation_period' => 3,
        'general_fee' => 15,
        'sameday_fee' => 25,
        'breakfast_price' => 17.50,
        'created_at' => now(),
        'updated_at' => now(),
      ],
    ]);
  }
}
