<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Hotel;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;


class HotelsTableSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    DB::table('hotels')->insert([
      [
        'user_id' => 2,
        'hotel_name' => 'Sunshine Hotel',
        'url' => 'https://sunshinehotel.com',
        'postal_code' => '108-0014',
        'prefecture' => 'Tokyo',
        'city' => 'Minato-ku',
        'street_address' => '5-27-1 Shiba',
        'address' => '5-27-1 Shiba, Minato-ku, Tokyo',
        'access' => '5 minutes from Tamachi Station. It is highly convenient and ideal as a base for both business and leisure.',
        'description' => 'Sunshine Hotel is conveniently located at 5-27-1 Shiba, Minato-ku, Tokyo, just minutes from major train stations. The hotel offers stunning city views and provides pregnancy-friendly amenities for expecting mothers. Families will appreciate spacious rooms with Wi-Fi, smart TVs, and modern facilities. Nearby attractions include Tokyo Tower and Hamarikyu Gardens, all within easy reach. Enjoy a comfortable stay with excellent service tailored to families and individuals alike.
',
        'image_main' => '',
        'image_sub1' => '',
        'image_sub2' => '',
        'image_sub3' => '',
        'image_sub4' => '',
        'cancellation_period' => 3,
        'general_fee' => 10,
        'sameday_fee' => 20,
        'breakfast_price' => 15.50,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      // 事前に登録しておく　Moonlight Inn
      [
        'user_id' => 4,
        'hotel_name' => 'Moonlight Inn',
        'url' => 'https://moonlightinn.com',
        'postal_code' => '150-0001',
        'prefecture' => 'Tokyo',
        'city' => 'Chuo-ku',
        'street_address' => '2-58-2 Hamacho, Nihonbashi',
        'address' => '2-58-2 Hamacho, Nihonbashi, Chuo-ku ,Tokyo',
        'access' => '3 minutes from Hamacho Station. Located in a vibrant area with easy access to shopping, dining, and entertainment hotspots, perfect for urban explorers.',
        'description' => 'Moonlight Inn is located at 2-58-2 Hamacho, Nihonbashi, Chuo-ku, Tokyo, offering excellent access just minutes from Hamacho Station. The hotel features wheelchair-friendly facilities, amenities for expecting mothers, and multilingual English-speaking staff. Guests enjoy modern rooms with Wi-Fi, smart TVs, and quality bedding, plus easy access to nearby attractions like Tokyo Skytree and Ginza. A variety of local shops and restaurants surround the hotel for added convenience. Experience personalized service and a welcoming stay at Moonlight Inn.',
        'image_main' => '',
        'image_sub1' => '',
        'image_sub2' => '',
        'image_sub3' => '',
        'image_sub4' => '',
        'cancellation_period' => 3,
        'general_fee' => 15,
        'sameday_fee' => 25,
        'breakfast_price' => 12.50,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'user_id' => 6,
        'hotel_name' => 'Star Hotel',
        'url' => 'https://starhotel.com',
        'postal_code' => '100-0002',
        'prefecture' => 'Kanagawa',
        'city' => 'Yokohama-shi',
        'street_address' => '1-1-1 Minato Mirai, Nishi-ku',
        'address' => '1-1-1 Minato Mirai, Nishi-ku, Yokohama-shi, Kanagawa ',
        'access' => 'A prime location, approximately a 5-minute walk from Minato Mirai Station. Convenient for both business and sightseeing.',
        'description' => 'Star Hotel offers breathtaking 360-degree ocean views, ensuring a serene and picturesque stay. Conveniently situated with excellent access to nearby train stations, its perfect for travelers seeking ease and comfort. Designed with inclusivity in mind, the hotel caters to wheelchair users, seniors, and those with visual or hearing impairments, providing thoughtful accommodations for all. Experience top-tier hospitality in a setting that combines beauty, accessibility, and convenience.',
        'image_main' => '',
        'image_sub1' => '',
        'image_sub2' => '',
        'image_sub3' => '',
        'image_sub4' => '',
        'cancellation_period' => 2,
        'general_fee' => 20,
        'sameday_fee' => 30,
        'breakfast_price' => 10.00,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'user_id' => 7,
        'hotel_name' => 'Galaxy Hotel',
        'url' => 'https://galaxyhotel.com',
        'postal_code' => '621-0034',
        'prefecture' => 'Kyoto',
        'city' => 'Kameoka City',
        'street_address' => 'Yunohana Onsen',
        'address' => 'Yunohana Onsen, Kameoka City, Kyoto',
        'access' => '30 minutes by the Sagano Line from JR Kyoto Station.',
        'description' => 'Welcome to Galaxy Hotel, nestled in the serene Yunohana Onsen area of Kameoka City, Kyoto. Our hotel is renowned for its breathtaking natural surroundings, offering a tranquil retreat for guests seeking relaxation. With wheelchair-accessible facilities, family-friendly amenities, and English-speaking staff, Galaxy Hotel ensures a comfortable stay for everyone, blending comfort with the beauty of nature.',
        'image_main' => '',
        'image_sub1' => '',
        'image_sub2' => '',
        'image_sub3' => '',
        'image_sub4' => '',
        'cancellation_period' => 2,
        'general_fee' => 25,
        'sameday_fee' => 35,
        'breakfast_price' => 18.00,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'user_id' => 8,
        'hotel_name' => 'Urban Suites',
        'url' => 'https://urbansuites.com',
        'postal_code' => '100-0004',
        'prefecture' => 'Tokyo',
        'city' => 'Shinagawa-ku',
        'street_address' => '1-50-5 Oi',
        'address' => '1-50-5 Oi, Shinagawa-ku, Tokyo',
        'access' => '4.1 km from Tokyo Oedo-Onsen Monogatari, 4.3 km from FCG Building, and just a 1-minute walk from Oi-Machi Station.',
        'description' => 'Urban Suites offers excellent access just a minutes walk from Oi-Machi Station. This family-friendly hotel provides a comfortable and relaxing environment for all guests, with English-speaking staff available to assist you. Whether you are visiting Tokyo for business or leisure, you will enjoy a peaceful stay with easy access to the citys attractions. Ideal for families, Urban Suites combines convenience and comfort in a vibrant urban setting.',
        'image_main' => '',
        'image_sub1' => '',
        'image_sub2' => '',
        'image_sub3' => '',
        'image_sub4' => '',
        'cancellation_period' => 5,
        'general_fee' => 10,
        'sameday_fee' => 20,
        'breakfast_price' => 20.00,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'user_id' => 9,
        'hotel_name' => 'Mountain Lodge',
        'url' => 'https://mountainlodge.com',
        'postal_code' => '089-2271',
        'prefecture' => 'Hokkaido',
        'city' => 'Hiroo District',
        'street_address' => '44-5 Kōchi-en, Taiki Town',
        'address' => '44-5 Kōchi-en, Taiki Town, Hiroo District, Hokkaido',
        'access' => '10 minutes from KitanomoriKitanomori Station. Set in a serene mountainous area, providing a perfect escape from the city.',
        'description' => 'Mountain Lodge, located at 44-5 Kōchi-en, Taiki Town, Hiroo District, Hokkaido, offers a peaceful retreat away from the hustle and bustle of the city. This family-friendly and religiously accommodating lodge provides a serene environment, perfect for relaxation and reflection. Surrounded by nature, guests can unwind in comfort, enjoying a tranquil stay. With a welcoming atmosphere for all, Mountain Lodge is ideal for families seeking a calm and restful escape. The lodge ensures a memorable experience for those looking to reconnect with nature.',
        'image_main' => '',
        'image_sub1' => '',
        'image_sub2' => '',
        'image_sub3' => '',
        'image_sub4' => '',
        'cancellation_period' => 4,
        'general_fee' => 15,
        'sameday_fee' => 25,
        'breakfast_price' => 17.50,
        'created_at' => now(),
        'updated_at' => now(),
      ],
    ]);
  }
}
